#!/bin/bash
# Manual instructions for fixing PostgreSQL authentication

echo "📝 Manual PostgreSQL Authentication Fix"
echo "=========================================="
echo ""
echo "Step 1: Find pg_hba.conf file"
echo "-------------------------------"
echo "Add PostgreSQL to PATH:"
echo "  export PATH=\"/usr/local/opt/postgresql@15/bin:\$PATH\""
echo ""
echo "Find the config file:"
echo "  psql -U postgres -d postgres -c \"SHOW hba_file;\""
echo ""
echo "Common locations:"
echo "  /usr/local/var/postgresql@15/pg_hba.conf"
echo "  /opt/homebrew/var/postgresql@15/pg_hba.conf"
echo ""
echo "Step 2: Edit pg_hba.conf"
echo "-------------------------"
echo "Add these lines at the TOP of the file (before other rules):"
echo ""
echo "  # Trust authentication for local development"
echo "  host    all             all             127.0.0.1/32            trust"
echo "  host    all             all             ::1/128                 trust"
echo ""
echo "Step 3: Restart PostgreSQL"
echo "---------------------------"
echo "  brew services restart postgresql@15"
echo ""
echo "Step 4: Test connection"
echo "------------------------"
echo "  export DATABASE_URL=\"postgresql://postgres@localhost:5432/postgres\""
echo "  export USE_FILE_STORAGE=\"false\""
echo "  python3 scripts/create_db_direct.py"
echo ""

